chore: create the signup view
TownHallHQ/TownHall pull request #207
Opened 2024-07-13 22:35 UTC by Michael-Liendo

2024-07-15 02:14 UTC, EstebanBorai requested changes

2024-07-15 02:14 UTC, EstebanBorai commented on crates/web/src/lib.rs
> +                <Route path="/login" view=Signup/>
Perhaps C/P?

```suggestion
                <Route path="/signup" view=Signup/>
```

2024-07-15 05:37 UTC, Michael-Liendo commented on crates/web/src/lib.rs
> +                <Route path="/login" view=Signup/>
yeah sorry, the speedy

2024-07-27 21:25 UTC, EstebanBorai reviewed
Small comments. Looks good overall!

2024-07-27 21:25 UTC, EstebanBorai commented on crates/web/src/components/auth/register.rs
> +use townhall_types::user::Email;
```suggestion
use std::str::FromStr;

use leptos::{
    component, create_action, create_rw_signal, create_signal, view, IntoView, Show, SignalGet,
    SignalGetUntracked, SignalSet,
};

use townhall_client::Client;
use townhall_types::user::Email;

use crate::components::text_field::{TextField, TextFieldType};
```

2024-07-27 21:25 UTC, EstebanBorai commented on crates/web/src/components/modal.rs
> +                <div class="fixed right-0 top-0 z-10 flex h-screen w-screen flex-col items-center justify-center drop-shadow-lg backdrop-blur-[2px] bg-[#00000055]">
I think `[#00000055]` could be translated to `bg-black/50`?

2024-07-27 21:29 UTC, EstebanBorai approved these changes

2024-07-27 23:21 UTC, merged